-- A lexical scanner generated by aflex
with text_io; use text_io;
with lexic_dfa; use lexic_dfa; 
with lexic_io; use lexic_io; 
--# line 1 "lexic.l"
-- Diferents macros que utilitzara l'analitzador lexic
-- Tots els caracters representables
-- Tots els caracters representables de la taula ascii menys
-- els caracters de les CometesDobles
--# line 15 "lexic.l"


with lexic_io; use lexic_io;
with lexic_dfa; use lexic_dfa;
with an_sintactic_tokens; use an_sintactic_tokens;
package a_lexic is
	function yylex return token;
end a_lexic;
